apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: api-customers
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        name: api-customers
    spec:
      containers:
      - name: api-customers
        image: gcr.io/ancient-yeti-166518/api-customers:latest
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 8001
