apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.api-customers: glob:commitId-*
  name: api-customers
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        name: api-customers
    spec:
      containers:
      - name: api-customers
        image: gcr.io/ancient-yeti-166518/customers:commitId-75968171a2818a627a0e52bd1e20fecd7dec8cd5
        ports:
        - containerPort: 8001
