apiVersion: v1
kind: Service
metadata:
  name: api-customers
  annotations:
    apicustomersclusterip: $API_CUSTOMERS_SERVICE_HOST
    apicustomersport: $API_CUSTOMERS_SERVICE_PORT
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  selector:
    name: api-customers
