apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.api-customers: glob:commitId-*
  name: api-customers
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        name: api-customers
    spec:
      containers:
      - name: api-customers
        image: gcr.io/ancient-yeti-166518/customers:commitId-c6420b4ee90159c56a93d8a4c4d8bbee4b4ba489
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
